/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg.financial_org_rating_system;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
