/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package financial_org_rating_system;

import org.junit.jupiter.api.Test;

import com.cg.financial_org_rating_system.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
